# Generated by Django 5.0.6 on 2024-05-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='key_duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
