# Generated by Django 5.0.4 on 2024-05-04 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14)),
                ('address', models.CharField(max_length=600)),
                ('country', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'male'), ('other', 'Preferred not to say')], max_length=8)),
                ('position', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
