# Generated by Django 5.0.6 on 2024-05-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_key_profile_key_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isEmailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
